export const CHARACTERS = [
  "Batman",
  "Beyoncé",
  "Captain Jack Sparrow",
  "Cleopatra",
  "Darth Vader",
  "Dorothy (Wizard of Oz)",
  "Dracula",
  "Einstein",
  "Elvis Presley",
  "Gandalf",
  "Harry Potter",
  "Indiana Jones",
  "James Bond",
  "Julius Caesar",
  "Mario",
  "Michael Jordan",
  "Napoleon",
  "Oprah",
  "Pikachu",
  "Ronald Reagan",
  "Sherlock Holmes",
  "Spider-Man",
  "SpongeBob",
  "Superman",
  "Wonder Woman",
];
