export const LOCATIONS = [
  "Airplane",
  "Bank",
  "Beach",
  "Casino",
  "Circus",
  "Cruise Ship",
  "Day Spa",
  "Embassy",
  "Fire Station",
  "Hospital",
  "Hotel",
  "Library",
  "Movie Studio",
  "Museum",
  "Ocean Liner",
  "Pirate Ship",
  "Polar Station",
  "Police Station",
  "Restaurant",
  "School",
  "Space Station",
  "Submarine",
  "Supermarket",
  "Theater",
  "University",
];
